version: "3.8"

services:
  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}_php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
        - INSTALL_XDEBUG=${INSTALL_XDEBUG}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

 # postgres:
 #   container_name: ${COMPOSE_PROJECT_NAME}_database
 #   build:
 #     context: ./postgres
 #   ports:
 #     - ${POSTGRES_PORT}:5432
 #   environment:
 #     POSTGRES_DB: ${COMPOSE_PROJECT_NAME}_${POSTGRES_DB}
 #     POSTGRES_USER: ${COMPOSE_PROJECT_NAME}_${POSTGRES_USER}
 #     POSTGRES_PASSWORD: ${COMPOSE_PROJECT_NAME}_${POSTGRES_PASSWORD}
 #   volumes:
 #     - db_data:/var/lib/postgresql/data:rw

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_database
    build:
      context: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}_${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql:rw

volumes:
  db_data: